#!/bin/sh
rsync -r /tmp/ScreamLite-installer/ScreamLite "$HOME/Library/Application Support/Cure Audio"
chown -R $USER:staff "$HOME/Library/Application Support/Cure Audio"

rm -rf /tmp/ScreamLite-installer/ScreamLite