; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
#define MyAppName "ScreamLite"
#define MyBusinessName "Cure Audio"

AppName={#MyAppName}
AppVersion={#MyVersion}
AppPublisher={#MyBusinessName}
AppPublisherURL=https://cure.audio
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
DefaultDirName={commonpf64}\{#MyBusinessName}\{#MyAppName}
DefaultGroupName={#MyAppName}
LicenseFile="..\LICENSE"
OutputDir="..\dist"
OutputBaseFilename={#MyAppName}_v{#MyVersion}
SetupIconFile=_windows_favicon.ico
; Useful dark mode examples https://jrsoftware.org/ishelp/index.php?topic=setup_wizardimagefile
; We force dark because its the only way to get white text, which is more legible against our custom background
WizardStyle=dark
; Setup Completed page image
WizardImageFile=.\_windows_WizardImageFile.png
WizardImageFileDynamicDark=.\_windows_WizardImageFile.png
; Logo in top right corner
WizardBackImageFile=.\_windows_WizardBackImageFile.png
WizardBackImageFileDynamicDark=.\_windows_WizardBackImageFile.png
; Logo in top right corner
WizardSmallImageFile=.\_windows_WizardSmallImageFile_DynamicDark.png
WizardSmallImageFileDynamicDark=.\_windows_WizardSmallImageFile_DynamicDark.png
; Minimum Windows version (Win 8) https://jrsoftware.org/ishelp/index.php?topic=setup_minversion
MinVersion=6.2

[Components]
; Note: This is a list of selectable "Components" for a user to install
; There is a dropdown menu will presets for isntallation types: full, compact, & custom.
Name: assets;      Description: Required Assets;  Types: full compact custom; Flags: fixed
Name: clap;        Description: CLAP Plugin;      Types: full
Name: vst3;        Description: VST3 Plugin;      Types: full compact

[Dirs]
Components: vst3; Name: "{commonpf64}\Common Files\VST3\{#MyAppName}.vst3"; Attribs: system
Components: clap; Name: "{commonpf64}\Common Files\CLAP"

[InstallDelete]
; Note: These icons are now obsolete. We used them before the svg rasteriser was added
Components: assets; Type: filesandordirs; Name: {userappdata}\{#MyBusinessName}\{#MyAppName}\cureaudio.png
Components: assets; Type: filesandordirs; Name: {userappdata}\{#MyBusinessName}\{#MyAppName}\icons.png
Components: vst3; Type: filesandordirs; Name: {commonpf64}\Common Files\VST3\{#MyAppName}.vst3
Components: clap; Type: filesandordirs; Name: {commonpf64}\Common Files\CLAP\{#MyAppName}.clap

[Files]
Components: assets; Source: "..\assets\Tomorrow-SemiBold.ttf";              DestDir: "{userappdata}\{#MyBusinessName}\{#MyAppName}";
Components: assets; Source: "..\assets\OFL.txt";                            DestDir: "{userappdata}\{#MyBusinessName}\{#MyAppName}";     DestName: Tomorrow-OFL.txt
Components: vst3;   Source: "..\build\Release\{#MyAppName}.vst3";           DestDir: "{commonpf64}\Common Files\VST3";                   Flags: recursesubdirs
Components: vst3;   Source: "..\assets\desktop.ini.in";                     DestDir: "{commonpf64}\Common Files\VST3\{#MyAppName}.vst3"; DestName: desktop.ini;     Attribs: system hidden
Components: vst3;   Source: "..\assets\PlugIn.ico";                         DestDir: "{commonpf64}\Common Files\VST3\{#MyAppName}.vst3";                            Attribs: system hidden
Components: clap;   Source: "..\build\Release\{#MyAppName}_plugin.dll";     DestDir: "{commonpf64}\Common Files\CLAP";                   DestName: {#MyAppName}.clap
